//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECourses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Favourite_Courses = new HashSet<Favourite_Courses>();
            this.Like_Courses = new HashSet<Like_Courses>();
            this.Subscription_Courses = new HashSet<Subscription_Courses>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public int Views { get; set; }
        public int Likes { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Course_Type_id { get; set; }
        public Nullable<int> City_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite_Courses> Favourite_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like_Courses> Like_Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription_Courses> Subscription_Courses { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual City City { get; set; }
        public virtual Course_Type Course_Type { get; set; }
    }
}
